#!/bin/bash

# prepare to print colorful text
red='\e[0;31m'
nc='\033[0m'

# print error messages
function err() {
  echo -e "${red}$@${nc}" # on red on stdout
  echo "[$(date +'%Y-%m-%dT%H:%M:%S%z')]: $@" >&2 # with timestamp on stderr
}

# run gazebo
function run_gazebo {
  cd Autobotz-Simulator/Bash/ # go to the right directory
  . Setup/VSS_setup.sh # run vss setup

  if [ $quiet ] ; then
    gzerver $world
  else
    gazebo $world --verbose
  fi
}

# run viewer
function run_viewer {
  cd Visao/ # go to the right directory

  if [ $viewer ] ; then
    python Vision.py
  fi
}

# run control
function run_control {
  cd Autobotz-Simulator/Modules/ # go to the right directory

  if [ $viewer ] ; then
    python Vision.py
  fi
}

# run script
function run() {

  # READ WORLD
  world=$1

  # check for errors while reading world
  if [ ! $world ] || [ "$world" == "-q" ] || [  "$world" == "-v" ]  || [  "$world" == "-c" ] ; then
    err "Please choose a world to open."
    exit 1
  fi

  world="Worlds/VSS_${world}.world" # append correct sintaxe

  # READ OPTIONS
  # default options values
  quiet=false
  viewer=false
  control=true

  # parse options
  OPTIND=2
  while getopts q:v:c: option; do
    case "${option}" in
      q) quiet=${OPTARG};;
      v) viewer=${OPTARG};set_viewer=true;;
      c) control=${OPTARG};;
    esac
  done

  # if quiet, viewer default become ture
  if [ $quiet ] && [ ! $set_viewer ] ; then
    viewer=true
  fi

  echo quiet = $quiet
  echo viewer = $viewer
  echo control = $control
}

run $@ 2>> Script/error.log # append error messages to log
