#!/bin/bash

# prepare to print colorful text
YELLOW='\033[1;33m'
GREEN='\033[0;32m'
NC='\033[0m'

#==============

# update submodules
echo -e "${YELLOW}Updating submodules:${NC}"
git supdate
echo -e "${GREEN}Done${NC}"

#==============

# compile plugins
echo -e "${YELLOW}Compiling Autobotz-Simulator plugins:${NC}"
cd Autobotz-Simulator/03_Plugins
python compile_all.py
echo -e "${GREEN}Done${NC}"
