#!/bin/bash

# prepare to print colorful text
YELLOW='\033[1;33m'
GREEN='\033[1;32m'
NC='\033[0m'

#==============

# update submodules
echo -e "${YELLOW}Updating submodules:${NC}"
git submodule update --remote --merge
echo -e "${GREEN}Done${NC}"

#==============

# compile plugins
echo -e "${YELLOW}Compiling Autobotz-Simulator plugins:${NC}"
cd Autobotz-Simulator/
script/compile all
cd ..
echo -e "${GREEN}Done${NC}"
